// DO NOT MODIFY OUTSIDE OF FLUID!!!
// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef gui_hpp
#define gui_hpp
#include <FL/Fl.H>
#include "callbacks.hpp"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Input.H>
extern Fl_Input *inputSymbol;
#include <FL/Fl_Table.H>
Fl_Double_Window* make_window();
#endif
