// DO NOT MODIFY OUTSIDE OF FLUID!!!
// generated by Fast Light User Interface Designer (fluid) version 1.0300

#include "gui.hpp"

Fl_Input *inputSymbol=(Fl_Input *)0;

static void cb_inputSymbol(Fl_Input* o, void*) {
  input_symbol_entered(o);
}

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(930, 670);
    w = o;
    { Fl_Tabs* o = new Fl_Tabs(0, 5, 930, 670);
      { Fl_Group* o = new Fl_Group(5, 30, 925, 645, "Quotes");
        { inputSymbol = new Fl_Input(65, 40, 95, 25, "Symbol:");
          inputSymbol->callback((Fl_Callback*)cb_inputSymbol);
          inputSymbol->when(FL_WHEN_ENTER_KEY);
        } // Fl_Input* inputSymbol
        { Fl_Table* o = new Fl_Table(10, 70, 915, 595);
          o->end();
        } // Fl_Table* o
        o->end();
      } // Fl_Group* o
      o->end();
    } // Fl_Tabs* o
    o->end();
  } // Fl_Double_Window* o
  return w;
}
