// DO NOT MODIFY OUTSIDE OF FLUID!!!
// generated by Fast Light User Interface Designer (fluid) version 1.0300

#include "gui.hpp"
using namespace cb;

Fl_Input *gInputSymbol=(Fl_Input *)0;

static void cb_gInputSymbol(Fl_Input* o, void*) {
  input_symbol_entered(o);
}

cb::QuoteTable *gTableQuote=(cb::QuoteTable *)0;

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(930, 670);
    w = o;
    o->labeltype(FL_NORMAL_LABEL);
    o->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    { Fl_Tabs* o = new Fl_Tabs(0, 5, 930, 670);
      { Fl_Group* o = new Fl_Group(5, 30, 925, 645, "Quotes");
        { gInputSymbol = new Fl_Input(65, 40, 95, 25, "Symbol:");
          gInputSymbol->callback((Fl_Callback*)cb_gInputSymbol);
          gInputSymbol->when(FL_WHEN_ENTER_KEY);
        } // Fl_Input* gInputSymbol
        { gTableQuote = new cb::QuoteTable(10, 70, 915, 595);
          gTableQuote->box(FL_THIN_DOWN_FRAME);
          gTableQuote->color(FL_BACKGROUND_COLOR);
          gTableQuote->selection_color(FL_BACKGROUND_COLOR);
          gTableQuote->labeltype(FL_NORMAL_LABEL);
          gTableQuote->labelfont(0);
          gTableQuote->labelsize(14);
          gTableQuote->labelcolor(FL_FOREGROUND_COLOR);
          gTableQuote->align(Fl_Align(FL_ALIGN_TOP));
          gTableQuote->when(FL_WHEN_RELEASE);
          gTableQuote->end();
        } // cb::QuoteTable* gTableQuote
        o->end();
      } // Fl_Group* o
      o->end();
    } // Fl_Tabs* o
    o->end();
  } // Fl_Double_Window* o
  return w;
}
